import { GoogleGenAI } from "@google/genai";
import OpenAI from "openai";
import Anthropic from "@anthropic-ai/sdk";
import { PlatformId, ProjectType, PromptHelperData, AIProvider } from "../types";
import { PLATFORMS } from "./platforms";

export const aiService = {
  buildInternalPrompt(
    userInput: string,
    platformId: PlatformId,
    projectType: ProjectType,
    helperData?: PromptHelperData,
    context?: string,
    isConversational: boolean = false
  ): string {
    const platform = PLATFORMS.find(p => p.id === platformId);
    
    let prompt = `You are "Indicator Forge AI", a specialist trading developer for ${platform?.name}.
Your goal is to help the user build professional ${projectType}s using ${platform?.language}.

PLATFORM-SPECIFIC RULES for ${platform?.name}:
- Use ${platform?.language} syntax.
- Follow best practices for ${platform?.name} (e.g., optimized loops, proper variable declaration).
- If a requested feature is unsupported in ${platform?.name}, explain it and suggest an alternative.

CORE BEHAVIOR:
${isConversational 
  ? `1. You are CONVERSATIONAL. If the user's request is vague, ask clarifying questions before writing code.
2. You can answer general trading and coding questions.`
  : `1. You are a CODE-ONLY generator. Your primary goal is to output functional code.
2. Avoid conversational filler. If the user asks a question, try to answer it within code comments or keep the explanation extremely brief.`}
3. When you provide code, you MUST wrap it in triple backticks with the language name (e.g., \`\`\`pinescript or \`\`\`cpp).
4. The UI will automatically extract code blocks and show them in a "Live Output" window.
5. Always include a subtle comment at the top of your code: "// Generated by Indicator Forge AI".

USER REQUEST:
${userInput}

${helperData ? `STRUCTURED DETAILS:
${helperData.timeframe ? `- Timeframe: ${helperData.timeframe}` : ''}
${helperData.entryConditions ? `- Entry Conditions: ${helperData.entryConditions}` : ''}
${helperData.exitConditions ? `- Exit Conditions: ${helperData.exitConditions}` : ''}
${helperData.riskManagement ? `- Risk Management: ${helperData.riskManagement}` : ''}
${helperData.visuals ? `- Visuals/Styling: ${helperData.visuals}` : ''}
` : ''}

${context ? `PREVIOUS CONTEXT:
${context}
` : ''}

OUTPUT GUIDELINES:
- If providing code: Provide the FULL code block.
- ${isConversational ? 'If clarifying: Be brief and professional.' : 'If the user is just chatting: Remind them you are here to forge code, but still provide the last generated code if applicable.'}
- Tone: Technical, helpful, and precise.
`;
    return prompt;
  },

  buildExplanationPrompt(code: string, platformId: PlatformId): string {
    const platform = PLATFORMS.find(p => p.id === platformId);
    return `Analyze the following ${platform?.name} script and provide a plain-English explanation for a retail trader.
Explain:
1. What the indicator does.
2. What inputs are configurable.
3. How signals are triggered.
4. How to interpret it on a chart.
5. Any limitations or assumptions.

Use beginner-friendly language.

CODE:
${code}`;
  },

  buildConversionPrompt(code: string, fromPlatformId: PlatformId, toPlatformId: PlatformId): string {
    const from = PLATFORMS.find(p => p.id === fromPlatformId);
    const to = PLATFORMS.find(p => p.id === toPlatformId);
    return `Convert the following ${from?.name} script to ${to?.name} (${to?.language}).
Requirements:
1. Preserve logic as closely as possible.
2. Flag any logic that cannot be translated exactly in comments.
3. Provide the FULL converted code block.
4. Add "Conversion Notes" at the end explaining any adjustments.

ORIGINAL CODE (${from?.name}):
${code}`;
  },

  buildAutoFixPrompt(code: string, errors: string, platformId: PlatformId): string {
    const platform = PLATFORMS.find(p => p.id === platformId);
    return `The following ${platform?.name} script has errors. Please fix them.
ERRORS:
${errors}

ORIGINAL CODE:
${code}

Provide the FULL corrected code block and a brief explanation of what was fixed.`;
  },

  async *generateCodeStream(provider: AIProvider, apiKey: string, internalPrompt: string) {
    if (provider === 'gemini') {
      const genAI = new GoogleGenAI({ apiKey: apiKey || process.env.GEMINI_API_KEY || '' });
      
      try {
        const response = await genAI.models.generateContentStream({
          model: "gemini-2.0-flash",
          contents: [{ role: 'user', parts: [{ text: internalPrompt }] }],
        });

        for await (const chunk of response) {
          if (chunk.text) {
            yield chunk.text;
          }
        }
      } catch (error) {
        console.error("Gemini Error:", error);
        throw error;
      }
    } else if (provider === 'openai') {
      const openai = new OpenAI({ apiKey, dangerouslyAllowBrowser: true });
      try {
        const stream = await openai.chat.completions.create({
          model: "gpt-4o",
          messages: [{ role: "user", content: internalPrompt }],
          stream: true,
        });
        for await (const chunk of stream) {
          const content = chunk.choices[0]?.delta?.content || "";
          if (content) yield content;
        }
      } catch (error) {
        console.error("OpenAI Error:", error);
        throw error;
      }
    } else if (provider === 'anthropic') {
      const anthropic = new Anthropic({ apiKey, dangerouslyAllowBrowser: true });
      try {
        const stream = await anthropic.messages.create({
          model: "claude-3-5-sonnet-20240620",
          max_tokens: 4096,
          messages: [{ role: "user", content: internalPrompt }],
          stream: true,
        });
        for await (const chunk of stream) {
          if (chunk.type === 'content_block_delta' && chunk.delta.type === 'text_delta') {
            yield chunk.delta.text;
          }
        }
      } catch (error) {
        console.error("Anthropic Error:", error);
        throw error;
      }
    }
  }
};
